repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: cd frontend && poetry run isort .
        language: system
        pass_filenames: false
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        entry: cd frontend && poetry run pyupgrade --py39-plus
        language: python
        types: [python]
        pass_filenames: true
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: cd frontend && poetry run black .
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: cd frontend && poetry run flake8 .
        language: system
        pass_filenames: false