repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: python scripts/poetry_run_wrapper.py frontend isort .
        language: python
        pass_filenames: false
  - repo: local
    hooks:
      -   id: pyupgrade
          name: pyupgrade
          entry: python scripts/pyupgrade_wrapper.py frontend
          language: python
          types: [python]
          pass_filenames: true
          files: ^frontend/.*$
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: python scripts/poetry_run_wrapper.py frontend black .
        language: python
        pass_filenames: false
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: python scripts/poetry_run_wrapper.py frontend flake8 .
        language: python
        pass_filenames: false