repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: bash -c "cd backend && poetry run isort ."
        language: system
        pass_filenames: false
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        entry: bash -c "cd backend && poetry run pyupgrade --py39-plus $(for file in $@; do echo \"../$file\"; done)" --
        language: python
        types: [python]
        pass_filenames: true
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: bash -c "cd backend && poetry run black ."
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: bash -c "cd backend && poetry run flake8 ."
        language: system
        pass_filenames: false