# Generated by Django 5.0.2 on 2024-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slides",
            name="image",
        ),
        migrations.AddField(
            model_name="slides",
            name="uploaded_file",
            field=models.FileField(upload_to="slides/"),
            preserve_default=False,
        ),
    ]
