# Generated by Django 5.0.2 on 2024-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_usersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="password",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="username",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="display_name",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="profile_picture",
            field=models.ImageField(
                default="default_profile_picture.jpg", upload_to="profile_pictures/"
            ),
        ),
    ]
