# Generated by Django 5.0.2 on 2024-03-22 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_usersettings_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("expired", "Expired")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("period", models.IntegerField()),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscriptions",
                        related_query_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subscribed users",
                    ),
                ),
            ],
        ),
    ]
