# Generated by Django 5.0.2 on 2024-03-22 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="users",
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                related_query_name="subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribed user",
            ),
        ),
    ]
