# Generated by Django 5.0.2 on 2024-03-22 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_subscription_users_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                related_query_name="subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribed user",
            ),
        ),
    ]
